name: Build Android APK (Ultra Compatible)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Ubuntu mais antigo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    
    - name: Setup Java JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK (Legacy)
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
    
    - name: Force Gradle 7.6 (Ultra Compatible)
      run: |
        cd android
        chmod +x gradlew
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip" > gradle/wrapper/gradle-wrapper.properties
    
    - name: Downgrade build settings
      run: |
        cd android
        sed -i 's/buildToolsVersion = "35.0.0"/buildToolsVersion = "33.0.0"/g' build.gradle
        sed -i 's/compileSdkVersion = 35/compileSdkVersion = 33/g' build.gradle
        sed -i 's/targetSdkVersion = 35/targetSdkVersion = 33/g' build.gradle
        sed -i 's/ndkVersion = "27.1.12297006"/ndkVersion = "23.1.7779620"/g' build.gradle
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps --force
    
    - name: Remove problematic packages
      run: |
        rm -rf node_modules/react-native-vibration
        rm -rf node_modules/react-native-sound
    
    - name: Create google-services.json
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "905864103175",
            "project_id": "apiifood-e0d35"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:905864103175:android:dummy",
                "android_client_info": {
                  "package_name": "com.cabanadelivery"
                }
              },
              "api_key": [
                {
                  "current_key": "AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease --stacktrace
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-legacy
        path: android/app/build/outputs/apk/release/app-release.apk
