name: Build Android APK (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Setup Java JDK 17 (Required for new Android SDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK (Corrected parameters)
      uses: android-actions/setup-android@v3
      with:
        packages: 'platforms;android-33 build-tools;33.0.0 ndk;23.1.7779620'
        accept-android-sdk-licenses: true
    
    - name: Force Gradle 7.6 + downgrade build config
      run: |
        cd android
        chmod +x gradlew
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.4-all.zip" > gradle/wrapper/gradle-wrapper.properties
        
        # Downgrade build settings to be compatible
        sed -i 's/buildToolsVersion = "35.0.0"/buildToolsVersion = "33.0.0"/g' build.gradle
        sed -i 's/compileSdkVersion = 35/compileSdkVersion = 33/g' build.gradle
        sed -i 's/targetSdkVersion = 35/targetSdkVersion = 33/g' build.gradle
        sed -i 's/ndkVersion = "27.1.12297006"/ndkVersion = "23.1.7779620"/g' build.gradle
    
    - name: Remove problematic dependencies before install
      run: |
        rm -rf node_modules/react-native-vibration || true
        rm -rf node_modules/react-native-sound || true
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --force --no-audit
    
    - name: Create google-services.json
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "905864103175",
            "project_id": "apiifood-e0d35"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:905864103175:android:dummy",
                "android_client_info": {
                  "package_name": "com.cabanadelivery"
                }
              },
              "api_key": [
                {
                  "current_key": "AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Fix Gradle classpath versions
      run: |
        cd android
        sed -i 's/classpath("com.android.tools.build:gradle")/classpath("com.android.tools.build:gradle:7.4.2")/g' build.gradle
        sed -i 's/classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")/classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10")/g' build.gradle
    
    - name: Clean and build APK
      run: |
        cd android
        ./gradlew clean --no-daemon
        ./gradlew assembleRelease \
          --no-daemon \
          --stacktrace \
          -Dorg.gradle.jvmargs="-Xmx3072m" \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true
      env:
        FLIPPER_DISABLE: 1
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-app
        path: android/app/build/outputs/apk/release/app-release.apk
