name: Build Android APK (Working Versions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'platforms;android-34 build-tools;34.0.0 ndk;25.1.8937393'
        accept-android-sdk-licenses: true
    
    - name: Force compatible Gradle version
      run: |
        cd android
        chmod +x gradlew
        # Gradle 8.3 é compatível com React Native 0.80.1
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip" > gradle/wrapper/gradle-wrapper.properties
    
    - name: Update build.gradle for compatibility
      run: |
        cd android
        # Usar versões compatíveis
        cat > build.gradle << 'EOF'
        buildscript {
            ext {
                buildToolsVersion = "34.0.0"
                minSdkVersion = 24
                compileSdkVersion = 34
                targetSdkVersion = 34
                ndkVersion = "25.1.8937393"
                kotlinVersion = "1.8.10"
            }
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath("com.android.tools.build:gradle:8.1.4")
                classpath("com.facebook.react:react-native-gradle-plugin")
                classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10")
                classpath 'com.google.gms:google-services:4.4.0'
            }
        }
        
        apply plugin: "com.facebook.react.rootproject"
        EOF
    
    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps
    
    - name: Remove problematic dependencies
      run: |
        rm -rf node_modules/react-native-vibration || true
        rm -rf node_modules/react-native-sound || true
    
    - name: Create google-services.json
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "905864103175",
            "project_id": "apiifood-e0d35"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:905864103175:android:dummy",
                "android_client_info": {
                  "package_name": "com.cabanadelivery"
                }
              },
              "api_key": [
                {
                  "current_key": "AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Clean and build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease --stacktrace --no-daemon
      env:
        FLIPPER_DISABLE: 1
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-working
        path: android/app/build/outputs/apk/release/app-release.apk
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-error-logs
        path: |
          android/app/build/outputs/logs/
          ~/.gradle/daemon/*/daemon-*.out.log
