name: Build with EAS (Expo Alternative)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install EAS CLI
      run: npm install -g @expo/cli eas-cli
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Create minimal app.json for EAS
      run: |
        cat > app.json << 'EOF'
        {
          "expo": {
            "name": "Cabana Delivery",
            "slug": "cabana-delivery",
            "version": "1.0.0",
            "platforms": ["android"],
            "android": {
              "package": "com.cabanadelivery",
              "versionCode": 1
            }
          }
        }
        EOF
    
    - name: Create eas.json
      run: |
        cat > eas.json << 'EOF'
        {
          "build": {
            "preview": {
              "android": {
                "buildType": "apk"
              }
            }
          }
        }
        EOF
    
    - name: Build with EAS
      run: eas build --platform android --profile preview --local --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Find and upload APK
      run: |
        find . -name "*.apk" -type f
        mkdir -p outputs
        find . -name "*.apk" -type f -exec cp {} outputs/ \;
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-eas
        path: outputs/*.apk
