name: Build Android APK (Ultra Safe)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    
    - name: Setup Java JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK (Manual - Ultra Safe)
      run: |
        export SKIP_JDK_VERSION_CHECK=true
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip -q commandlinetools-linux-6858069_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "SKIP_JDK_VERSION_CHECK=true" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "y" | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"
    
    - name: Completely rewrite android build files
      run: |
        cd android
        chmod +x gradlew
        
        # Force Gradle 7.4.2 (ultra safe)
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-all.zip" > gradle/wrapper/gradle-wrapper.properties
        
        # Rewrite root build.gradle
        cat > build.gradle << 'EOF'
        buildscript {
            ext {
                buildToolsVersion = "33.0.0"
                minSdkVersion = 21
                compileSdkVersion = 33
                targetSdkVersion = 33
                ndkVersion = "21.4.7075529"
            }
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath("com.android.tools.build:gradle:7.2.1")
                classpath("com.facebook.react:react-native-gradle-plugin")
                classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
                classpath 'com.google.gms:google-services:4.3.13'
            }
        }

        allprojects {
            repositories {
                google()
                mavenCentral()
                maven { url "https://www.jitpack.io" }
            }
        }
        EOF
    
    - name: Install and fix dependencies
      run: |
        npm install --legacy-peer-deps --force
        rm -rf node_modules/react-native-vibration
        rm -rf node_modules/react-native-sound
    
    - name: Create google-services.json
      run: |
        mkdir -p android/app
        echo '{"project_info":{"project_number":"905864103175","project_id":"apiifood-e0d35"},"client":[{"client_info":{"mobilesdk_app_id":"1:905864103175:android:dummy","android_client_info":{"package_name":"com.cabanadelivery"}},"api_key":[{"current_key":"AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"}]}]}' > android/app/google-services.json
    
    - name: Build APK
      run: |
        cd android
        ./gradlew clean assembleRelease --no-daemon --stacktrace
      env:
        SKIP_JDK_VERSION_CHECK: true
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-ultra-safe
        path: android/app/build/outputs/apk/release/app-release.apk
