name: Build Android APK (No Modifications)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Volta para versão mais antiga e estável
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18 (Exact version from package.json)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Accept ALL Android licenses
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update || true
    
    - name: Install EXACT dependencies (no modifications)
      run: |
        npm ci
    
    - name: Create minimal google-services.json only
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "905864103175",
            "project_id": "apiifood-e0d35"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:905864103175:android:dummy",
                "android_client_info": {
                  "package_name": "com.cabanadelivery"
                }
              },
              "api_key": [
                {
                  "current_key": "AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Build APK (no modifications to gradle files)
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean assembleRelease --no-daemon --stacktrace
      env:
        FLIPPER_DISABLE: 1
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-simple
        path: android/app/build/outputs/apk/release/app-release.apk
