name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK (Conservative)
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
    
    - name: Force Gradle 8.6 (Compatible)
      run: |
        cd android
        chmod +x gradlew
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip" > gradle/wrapper/gradle-wrapper.properties
    
    - name: Update Android Gradle Plugin (Compatible)
      run: |
        cd android
        sed -i 's/buildToolsVersion = "35.0.0"/buildToolsVersion = "34.0.0"/g' build.gradle
        sed -i 's/compileSdkVersion = 35/compileSdkVersion = 34/g' build.gradle
        sed -i 's/targetSdkVersion = 35/targetSdkVersion = 34/g' build.gradle
    
    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps
    
    - name: Remove problematic dependencies
      run: |
        rm -rf node_modules/react-native-vibration || true
    
    - name: Create google-services.json
      run: |
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "905864103175",
            "project_id": "apiifood-e0d35"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:905864103175:android:dummy",
                "android_client_info": {
                  "package_name": "com.cabanadelivery"
                }
              },
              "api_key": [
                {
                  "current_key": "AIzaSyBuRHTtuKgpQE_qAdMIbT9_9qbjh4cbLI8"
                }
              ]
            }
          ]
        }
        EOF
    
    - name: Clean project
      run: |
        cd android
        ./gradlew clean --warning-mode all
    
    - name: Build APK with compatibility flags
      run: |
        cd android
        ./gradlew assembleRelease \
          --warning-mode all \
          --stacktrace \
          -Dorg.gradle.jvmargs="-Xmx4096m" \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true
      env:
        FLIPPER_DISABLE: 1
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cabana-delivery-app
        path: android/app/build/outputs/apk/release/app-release.apk
